### ISSUE TITLE
about duelist special ability

### ISSUE THREAD

**Issue by nupnuts** [Hoto-Mocha/Re-ARranged-Pixel-Dungeon#19]
Is this normal? when the duelist has charge, he can use it to reload the gun.

**Comment by nupnuts** [comment]
https://github.com/Hoto-Mocha/Re-ARranged-Pixel-Dungeon/assets/122851547/7762eceb-d464-4f23-bbc6-83f3d865881d


https://github.com/Hoto-Mocha/Re-ARranged-Pixel-Dungeon/assets/122851547/983c7fe8-5481-4fb3-b7b4-52e52ad3ab75

**Comment by Hoto-Mocha** [comment]
Duelist's gun ability is "Fast Reload", which performs instant reload without spending ammo and turn.
If the gun's round is full or over the maximun, Fast Reload can 'Over Reload' up to twice of its maximum round.
You can check if the fast reload is ready with the color of its round. Blue = you have enough weapon energy to use fast reload.
So it is not a bug, and it performs very well.
