### ISSUE TITLE
IOS 빌드 관련 수정 문의

### ISSUE THREAD

**Issue by kdy565** [Hoto-Mocha/Re-ARranged-Pixel-Dungeon#20]
ios/src/main/java/com/shatteredpixel/shatteredpixeldungeon
를

ios/src/main/java/com/rearrangededpixel/rearrangedpixeldungeon

으로 수정하고,

build.gradle 폴더에서 패키지명 com.rearrangedpixel.rearrangedpixeldungon 에서 오타(dungeon)을 수정해주시길 바랍니다.

ios를 위해 RoboVM으로 빌드할때 오류를 해결할 수 있습니다

**Comment by Hoto-Mocha** [comment]
패키지명에 오타가 있는 것은 안타까운 일이지만, 
패키지명을 변경하면 기존에 배포하던 애플리케이션을 스토어에서 배포 중지하고 다시 발행해야 하기 때문에 그 부분은 어려울 것 같습니다.

**Comment by Hoto-Mocha** [comment]
그리고 폴더명을 바꾸는 것이 필수적인 일인지 잘 모르겠네요. 안드로이드의 경우 폴더명이 패키지명이랑 달라도 상관이 없는데, ios는 안 그런 건가요?

이전에 SPD 개발자 Evan에게 폴더명을 바꾸어야 하는지에 대해 물어봤었는데, 안 바꿔도 괜찮다고 답변을 받았습니다.
![image](https://github.com/Hoto-Mocha/Re-ARranged-Pixel-Dungeon/assets/76470428/94ba40df-e8d8-4a03-b0f0-57a9bcfb0f90)

**Comment by Hoto-Mocha** [comment]
이건 필수는 아닌데, 빠른 답변을 원하시면 게임 내의 디스코드를 통해서 연락을 주시면 제가 바로 확인이 가능합니다.
