### ISSUE TITLE
콘솔명령에 대한기능요청 정보

### ISSUE THREAD

**Issue by zay448345045** [Hoto-Mocha/Re-ARranged-Pixel-Dungeon#23]
개발자가다른지하감옥과마찬가지로개발자모드의기능을추가할수있습니까?
![IMG_20240519_181441](https://github.com/Hoto-Mocha/Re-ARranged-Pixel-Dungeon/assets/22346235/28071a75-0431-48b0-8716-b435743d6b7e)

**Comment by Hoto-Mocha** [comment]
Check this: https://github.com/Hoto-Mocha/Re-ARranged-Pixel-Dungeon/blob/master/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/Teleporter.java

**Comment by zay448345045** [comment]
> The game already contains a item for testing, but it is now unreachable. It will be fixed in the next version Check this for the code: https://github.com/Hoto-Mocha/Re-ARranged-Pixel-Dungeon/blob/master/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/Teleporter.java

Yes, I have tried adding console to shattered pixel dungeons and using Lua to call Java functions, which works fine. With this, it will be more convenient for players to study game content.
![Screenshot_2024-05-21-14-39-28-228_com shatteredpixel shatteredpixeldungeonlua indev-edit](https://github.com/Hoto-Mocha/Re-ARranged-Pixel-Dungeon/assets/22346235/00df02d0-6736-440a-9bee-acd01ae3ccb8)
