### ISSUE TITLE
장신구 아이디어

### ISSUE THREAD

**Issue by Hoto-Mocha** [Hoto-Mocha/Re-ARranged-Pixel-Dungeon#28]
- [x] 마법의 나침반 - 층 진입 시 확률적으로 입구부터 출구까지의 경로를 밝힘
- [x] 신비한 수정구 - 층 진입 시 확률적으로 모든 아이템의 위치를 드러내며, 매우 낮은 확률로 맵 전체를 밝힘
- [x] 깨진 돋보기 - 이동 시 숨겨진 문을 찾을 확률을 늘리지만 숨겨진 함정을 찾을 확률을 감소시킴
- [x] 수상한 열쇠 - 비밀방 생성 개수를 늘리지만 문이 숨겨질 확률을 증가시킴
- [x] 분홍색 보석 - 적 처치 시 무작위 아이템을 드랍할 확률이 생기지만 기존 드랍 확률을 감소시킴
- [x] 보석 목걸이 - 반지를 소비해 목걸이에 넣을 수 있으며, 해당 반지 효과를 장신구 강화수치만큼 받음
- [ ] 마법의 숫돌 - 기습 시  
- [ ] 물약 주입 탄환 - 물약을 사용해 총탄에 특별한 기능을 추가할 수 있음. 강화할수록 효과가 사라지기까지의 발사 수가 증가

**Comment by nupnuts** [comment]
These things remind me of Munchers. 
![Uploading 企业微信截图_20240530120315.png…]()
