### ISSUE TITLE
버그제보

### ISSUE THREAD

**Issue by ahls** [Hoto-Mocha/Re-ARranged-Pixel-Dungeon#34]
트롤대장장이와 도서관? 입구가 같이 생성되면, 트롤대장장이 임무를 하고 나오는 길에 도서관 입구로 이동됩니다.

트롤 퀘스트는 흙점쟁이 사냥 이였구용

**Comment by ahls** [comment]
도적 보급 식량 스프라이트가 없어요!
둘다 3.9 문제이긴 한데, 릴리즈 노트에 따로 언급되지 않은거같습니당. 항상 감사합니다!

**Comment by Hoto-Mocha** [comment]
v3.11.0에서 수정했습니다.
