### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by lightspect** [Hoto-Mocha/Re-ARranged-Pixel-Dungeon#38]
![Screenshot_20240725-205407_Rearranged Pixel Dungeon](https://github.com/user-attachments/assets/a3f39656-0d76-47d4-9777-1560fd4baac3)
When brewing in alchemist pot, cannot make blueprint even when auto choose or manual choosing items

**Comment by lightspect** [comment]
Achievement for Knight unlocking: No text found
![Screenshot_20240725-210241_Rearranged Pixel Dungeon](https://github.com/user-attachments/assets/7ebd05b5-b3be-4391-93f3-c3ae11f169b2)

**Comment by lightspect** [comment]
Cannot use old amulet on any weapon, always return nothing seems to have changed
![Screenshot_20240725-213930_Rearranged Pixel Dungeon](https://github.com/user-attachments/assets/f0dfda54-7170-4518-a7a0-ea3fef4d0dcf)

**Comment by Hoto-Mocha** [comment]
the first one and third one is not bug. blueprints have their own specific recipes, and auto selection chooses just random weapon in your backpack. and samurai's mold amulet feature is not implemented yet.

**Comment by lightspect** [comment]
When using Force Gloves on enemies next to you, NO text found
![Screenshot_20240817-031522_Rearranged Pixel Dungeon](https://github.com/user-attachments/assets/366974db-a7e0-43b5-ba09-42928102ed06)

**Comment by lightspect** [comment]
![Screenshot_20240817-032615_Rearranged Pixel Dungeon](https://github.com/user-attachments/assets/7d8a49ca-1391-4bf9-827b-374d2c27ff51)
Master of all trade achievement: No text found even if all jobs are listed

**Comment by Hoto-Mocha** [comment]
all problem have been fixed. thanks
