### ISSUE TITLE
I think critical bug report...

### ISSUE THREAD

**Issue by EngiGaming-tf2** [Hoto-Mocha/Re-ARranged-Pixel-Dungeon#39]
Dear modification developer, I noticed a bug where it was impossible to select subclass abilities when using the crown from the boss "Dwarf King" and when choosing one of the abilities, the game broke down and turned off, please correct the error and finally translate your modification! :]

**Comment by Hoto-Mocha** [comment]
fixed in v3.11.1. thank you for report!
