### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by EngiGaming-tf2** [Hoto-Mocha/Re-ARranged-Pixel-Dungeon#42]
_**Honorable**_ developer of this modified game, there is a question about the version of the game, when an update is released on github, does this affect the game itself in the play store? Or not? if not, do I need to download the github version of the game over the playmarket version?

**Comment by Hoto-Mocha** [comment]
The game that is getting uploaded on Google Play Store is exactly same with the game in github release.
The game that is getting uploaded to the Google Play Store takes some time to be updated, as it takes time for the game to be reviewed and compiled for each device.

**Comment by EngiGaming-tf2** [comment]
**Thanks** **for** **asking** + _Question/Issue._ 
 I can't download the version of the game from your github, when downloading the file for half, I think he writes - Authorization is required, and after he writes that the file could not be downloaded
