### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by EngiGaming-tf2** [Hoto-Mocha/Re-ARranged-Pixel-Dungeon#45]
Dear developer, I believe that the 5th boss, who is a military boss, is very strong and it is 
 **impossible** to defeat him, he is treated **endlessly,** summons **endless** hordes of other soldiers and medics. And what we get is a boss that can't be killed at all... As a player who got there with a lot of healing potions and **level 30** on a  __knight__

**Comment by EngiGaming-tf2** [comment]
Any tips how to kill him _**effective**_?

**Comment by jazzcat86** [comment]
여기에 제보하는게 맞는지 모르겠네요... 이미 아실 수도 있겠지만, 결투자 2-6 특성에 포인트를 투자해도 아무 변화가 없습니다. 주무기의 최대 충전량이 오른다는게 툴팁이네요!
