### ISSUE TITLE
연구자 3-10 수분흡수 특성이 설명과 다르네요

### ISSUE THREAD

**Issue by thunderwhale3015** [Hoto-Mocha/Re-ARranged-Pixel-Dungeon#48]
https://github.com/Hoto-Mocha/ARranged-Pixel-Dungeon/issues/346
여기에 잘못 올린거 다시 올립니다.

![357946451-1b0b9925-be73-4455-87f0-02fd4fd5153c](https://github.com/user-attachments/assets/43530314-1d8b-4b94-a1ed-b9d63f5691c3)

설명에서는 분명 해당 특성으로 이슬이 나온다고 하였는데

https://www.youtube.com/watch?v=-wETX8l5WTs&feature=youtu.be

이 영상의 16초, 3분 19초와 같이 이슬이 아닌 씨앗이 드랍됩니다. 나머지 부분을 보시면 아시겠지만 다른 것은 드랍되지 않았습니다.
제 생각에는 설명문만 이슬 -> 씨앗으로 바꾸면 충분할 거 같습니다.

![357945203-a410b36d-2085-4580-a4c8-96588f25f91b](https://github.com/user-attachments/assets/f1ab93be-a0b5-445a-a8d6-4b89f9d3ac13)

특성은 위와 같이 찍었고, 레벨 18, 신성한 영감의 영약으로 3티어 특성만 2개 늘린 상태입니다.
챌린지는 돌연변이챌만 걸었습니다.

**Comment by Hoto-Mocha** [comment]
v3.12.0에서 수정 완료했습니다. 감사합니다.
