### ISSUE TITLE
기사 1-1 특성 무한적용 됩니다.

### ISSUE THREAD

**Issue by thunderwhale3015** [Hoto-Mocha/Re-ARranged-Pixel-Dungeon#52]
https://www.youtube.com/watch?v=_5JbCMVbA5Q&feature=youtu.be

3.12.0버전 기준입니다.
위 영상 5초쯤에서 기사 1-1 특성으로 2회 맞는 동안 방어력 3~3 더해진 상태입니다.
2회 맞고 난 뒤인 11초쯤에서 버프 여전히 유지되고 있습니다.
아마 기사가 맞을 때 줄어들어야 하는 값이 줄어들고 있지 않은 거 같아요.

**Comment by Hoto-Mocha** [comment]
v3.14.0에서 수정했습니다. 감사합니다.
