### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by lightspect** [Hoto-Mocha/Re-ARranged-Pixel-Dungeon#61]
**Version name (required)**.
Write the version name as follows(exclude SPD's version name): v3.15.0

**Bug description (required)**
When press on the second tab in the journal in the main menu screen, the game crash

**How to reproduce the bug (required)**
Open the game
Go to Journal
Select second tab from the left

**How is it supposed to be (required)**
Displaying the second tab without crashing the game

**Screenshots**
![Screenshot_20240917-173000_Rearranged Pixel Dungeon](https://github.com/user-attachments/assets/264be587-cd3c-4fc4-a9d4-9ca393afb993)

**Anything else**
Also the tab for the pills in Alchemy is overflowing

**Comment by Hoto-Mocha** [comment]
fixed in v3.15.1. thanks
