### ISSUE TITLE
성검에 숙련의 물약 적용이 안됨

### ISSUE THREAD

**Issue by rhtjswl113** [Hoto-Mocha/Re-ARranged-Pixel-Dungeon#62]
**Version name (required)**.
Write the version name as follows(exclude SPD's version name): v3.15.0

**Bug description (required)**
성검에 숙련의 물약을 사용해도 요구 힘 수치가 24임

**How to reproduce the bug (required)**
The steps you need to take to reproduce the bug again.
성검에 숙련물약 사용하기
**How is it supposed to be (required)**
A description of how things should have worked originally if the bug didn't happen.
힘 요구수치가 22가 돼야함
**Screenshots**
Screenshots can be an important piece of information. Please show the screen as it is, without cropping or editing anything you think is unnecessary - that can be a clue.

**Anything else**
Anything else you can add to supplement the report

**Comment by rhtjswl113** [comment]
실험결과 쌍특대검, 전술방패 등 몇몇 7티어 무기에 숙련의 물약이 적용되지 않는것을 추가로 확인했음.
랜스방패는 숙련의물약이 적용됨
근데 7티어 무기들 이름을 다 알질 못해서 저거 세개밖에 추가로 못해봤음

**Comment by Hoto-Mocha** [comment]
v3.15.1에서 수정 완료
