### ISSUE TITLE
Potion of Mastery not working on Holy Sword

### ISSUE THREAD

**Issue by lightspect** [Hoto-Mocha/Re-ARranged-Pixel-Dungeon#63]
**Version name (required)**.
Write the version name as follows(exclude SPD's version name): v3.15.0

**Bug description (required)**
Apply the potion of mastery on Holy Sword but the strength requirement is not dropping

**How to reproduce the bug (required)**
Apply the potion of mastery on Holy Sword

**How is it supposed to be (required)**
Holy Sword strength requirement drop to 22

**Screenshots**
![Screenshot_20240918-180711_Rearranged Pixel Dungeon](https://github.com/user-attachments/assets/38414752-933a-40e1-a8be-1bf2f9ec5236)

**Anything else**
None

**Comment by Hoto-Mocha** [comment]
fixed in v3.15.1. thanks
