### ISSUE TITLE
Missing Chinese translation

### ISSUE THREAD

**Issue by RuSuanJun666** [Hoto-Mocha/Re-ARranged-Pixel-Dungeon#64]
Hello developer, I noticed that the Chinese translation in the game is not perfect, mainly reflected in the gun module, jewelry module, hero talent name and talent introduction, can you help improve the translation?

**Comment by Hoto-Mocha** [comment]
sorry, the chinese translation is not supported in this game, because the translation work requires so much time

**Comment by Hoto-Mocha** [comment]
checking this might be helpful: https://github.com/1015561267/Re-ARranged-Pixel-Dungeon-CN

**Comment by RuSuanJun666** [comment]
Thanks, this is very helpful for me&nbsp;


?(ˊωˋ*)??
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月20日(星期五) 下午2:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Hoto-Mocha/Re-ARranged-Pixel-Dungeon] Missing Chinese translation (Issue #64)





 
checking this might be helpful: https://github.com/1015561267/Re-ARranged-Pixel-Dungeon-CN
 
&mdash;
