### ISSUE TITLE
An error of v3.15.1-desktop.jar

### ISSUE THREAD

**Issue by CarlRyou** [Hoto-Mocha/Re-ARranged-Pixel-Dungeon#67]
Version：
v3.15.1-desktop.jar

Character
APD soldier for specialist and enhanced aromr (second job, I'm not sure it's this name),

Challenge：
superman challenge mod is on

Equipment：
I got a elderich machine gun+1
voicosty  plate armor +5 for hero's aromr
I got no artifacts
ring of sharpshooting+3 ring of wealth+9 
Crystal of wealth+3 for trinkets

Progress：
I'v get to floor 27 and got the old ascension

Error
this error happened after I upgrading ring of sharpshooting from +2 to +3 , witch should further improve my shooting damage
However it seems decrease the damage, or, I mean superman mod failed. Damage back to 3~17 but not 9~51
I tried to back to main menu and exit to refresh it, and error happened when I try to load the save again

Trait：
Further more, I transmuted several trait, but I can't really name out all of them correctly (I'm a Chinese player)
Tier 1 
gun melee → tier 1 trait 3 of knight 
indentify trait → war cry
Tier 2
melee reload → tenacity trait of knight
invisible after step on grass → mind vision of huntress
scroll trait → blocking trait of warrier

Others：
You forgot to change the email address listed here😂

I hope my description of this error is helpful to you
![QQ20240928-222050](https://github.com/user-attachments/assets/e9fc5bac-eea8-4f33-8a5d-f733e2f610b6)

**Comment by Hoto-Mocha** [comment]
Fixed in v3.16.0, but needs to check if it works
