### ISSUE TITLE
거너 1-5특성이 오표기되었거나 잘못 적용되고있음.

### ISSUE THREAD

**Issue by rhtjswl113** [Hoto-Mocha/Re-ARranged-Pixel-Dungeon#68]
**버전 이름(필수)**
버전 이름은 다음과 같이 작성합니다(녹픽던의 버전 이름은 작성하지 않습니다). v3.14.0

**버그 설명(필수)**
총기 근접 대미지 증가가 0-4 0-6이 아닌 0-1 0-2로 적용되고있음.

**버그 재현 방법(필수)**
거너 1-5특성 찍기

**원래 어때야 하는지(필수)**
대미지 올려줘잉
**스크린샷**

**그 외**
리포트 내용을 보충할 수 있는 내용 추가

**Comment by rhtjswl113** [comment]
재확인결과, 0-4 0-6이 안늘고 0-1 0-2가 늘어남
특성의 표기 오류인가 수치 적용 오류인지 아니면 티어마다 다르게 늘어나는지 모르겠읆..

**Comment by Hoto-Mocha** [comment]
v3.16.0에서 수정완료
