### ISSUE TITLE
숙련의 물약 미적용이 7티어에만 한정된게 아니었나봄

### ISSUE THREAD

**Issue by rhtjswl113** [Hoto-Mocha/Re-ARranged-Pixel-Dungeon#69]
**Version name (required)**.
Write the version name as follows(exclude SPD's version name): v3.14.0

**Bug description (required)**
3티어 무기 돌격소총에도 적용되지 않는것을 확인했음
**How to reproduce the bug (required)**
돌격소총에 숙련의 물약 적용이 안됨, 안되는 무기들이 더 있을듯함

**How is it supposed to be (required)**
A description of how things should have worked originally if the bug didn't happen.
3강 돌격소총에 숙련의 물약을 적용하였기에 요구 힘 수치가 10이 돼야함.
**Screenshots**
Screenshots can be an important piece of information. Please show the screen as it is, without cropping or editing anything you think is unnecessary - that can be a clue.
![Screenshot_20241012_044939](https://github.com/user-attachments/assets/027b3aad-eac0-4925-a816-5db813d7b18c)

**Anything else**
Anything else you can add to supplement the report

**Comment by Hoto-Mocha** [comment]
v3.16.0에서 수정완료
