### ISSUE TITLE
기사 1-3 특성 버그 제보

### ISSUE THREAD

**Issue by AstraeasAbacus** [Hoto-Mocha/Re-ARranged-Pixel-Dungeon#71]
**버전 이름(필수)**
v3.16.0 

**버그 설명(필수)**
1-3 특성이 처치시가 아닌 공격시 적용되고 있음

**버그 재현 방법(필수)**
아래 쇼츠 영상 참고
몹 치면서 버프생기는 것을 확인했습니다. 데미지도 쎄게 들어가는걸 봐서는 잘못 표시된 버프도 아닌듯 싶네요.
https://youtube.com/shorts/57m8XdEj6S0?si=7XIXM1sIrw3dD-NI

**원래 어때야 하는지(필수)**
특성란에서는 적을 처치해야 버프가 생긴다고 적혀있습니다.

**스크린샷**
(위의 쇼츠 참고해주세요)

**그 외**
-

**Comment by Hoto-Mocha** [comment]
v3.17.0에서 수정 완료했습니다. 감사합니다.
