### ISSUE TITLE
I hate blueprint

### ISSUE THREAD

**Issue by Aaaaaa-debug** [Hoto-Mocha/Re-ARranged-Pixel-Dungeon#74]
Blueprint needs more things with lesser chance to craft strong weapons, extremely bad for collecting

**Comment by Aaaaaa-debug** [comment]
success rate of blueprint needs to turn it back to that... 
![8446B1C2AD96F123130DFC3A0C170A1C](https://github.com/user-attachments/assets/08e04c24-e26c-41ea-a178-70ee98f075e0)

**Comment by Hoto-Mocha** [comment]
you can upgrade it to increase success chance if you really need to make it
