### ISSUE TITLE
Ring of Wealth and Pink gem interaction

### ISSUE THREAD

**Issue by lightspect** [Hoto-Mocha/Re-ARranged-Pixel-Dungeon#76]
How does RoW and Pink gem interact with each other? 
I have a +0 RoW and and chose Pink Gem as my trinket.

**Comment by Hoto-Mocha** [comment]
For enemy drop(like dropping golds from Gnoll) chance, it does interact with each other. for example, 10%(the enemy's default drop chance) * x3 (RoW multiflier) * x0 (Pink Gem +3 multiplier) = 0%
But for additional drop(dropping items with flare) mechanism, it acts indivisually.

**Comment by lightspect** [comment]
So what would happened if I upgrade the Pink gem to +3? Does it still stop the enemies from dropping normal items? What about bonus items? If I upgraded my ring to +10, will it still drop +5 items?

**Comment by Hoto-Mocha** [comment]
I already answered for that question. please check again.

**Comment by lightspect** [comment]
So for example, if I have a +0 pink gem, the drop will be
10% × 0.8 × 3 = 24% for normal items, but for extra items like weapons and armor, if I have +10 RoW and +0 pink gem, then it does not stack and only produce +5 items correct? What is the rate for extra items may I ask?

**Comment by Hoto-Mocha** [comment]
Addtional item drop mechanism doesn't interact with each other like RoW and Pink Gem, so it will act totally indivisually like you only have RoW or Pink Gem. don't worry about it. About Pink Gem drop mechanism, you can check the code [here.](https://github.com/Hoto-Mocha/Re-ARranged-Pixel-Dungeon/blob/master/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/trinkets/PinkGem.java)

**Comment by Hoto-Mocha** [comment]
The Pink Gem drops consumables like you are equipping RoW, but it dose NOT actually provide you real effect of RoW equipment.

**Comment by Hoto-Mocha** [comment]
For saying easily, it's mechanism is same with the Lucky enchantment, and it acts totally individually, too.

**Comment by lightspect** [comment]
I understand now. Thanks. So overall for items that monster normally drop, like gold and health potion, the pink gem is detrimental to RoW because at +3, it will reduce the drop to 0% despite the RoW level. But for extra items, then it act as a +10 RoW but with luck enchantment generation, meaning no weapons or armor. 
You can close this issue now
