### ISSUE TITLE
medical officer 3-10 bug

### ISSUE THREAD

**Issue by sjsxmd** [Hoto-Mocha/Re-ARranged-Pixel-Dungeon#77]
**Version name (required)**.
Write the version name as follows(exclude SPD's version name): v3.17.0

**Bug description (required)**
I upgrade 3-10 to +3，promote command need 3 charges instead of 1 charges

**How to reproduce the bug (required)**
don't know.

**How is it supposed to be (required)**
promote command need 1 charges

**Screenshots**
![Screenshot_20241227_115813_com_rearrangedpixel_rearrangedpixeldungon_AndroidLaunch](https://github.com/user-attachments/assets/b409a3e9-3f9f-440b-9941-14dfbcbe465f)
![Screenshot_20241227_115809_com_rearrangedpixel_rearrangedpixeldungon_AndroidLaunch](https://github.com/user-attachments/assets/a683034d-621b-4297-b4bd-ab53b208cb70)

**Anything else**
Anything else you can add to supplement the report

**Comment by Hoto-Mocha** [comment]
fixed in v3.18.0. thanks.
