### ISSUE TITLE
first aid kit bug

### ISSUE THREAD

**Issue by sjsxmd** [Hoto-Mocha/Re-ARranged-Pixel-Dungeon#78]
**Version name (required)**.
Write the version name as follows(exclude SPD's version name): v3.17.0

**Bug description (required)**
I upgrade first aid kit to +10, but it can't immune to debuff.

**How to reproduce the bug (required)**
don't know.

**How is it supposed to be (required)**
when the guard pull medic close，Medic can't get cripe debuff.

**Screenshots**

https://github.com/user-attachments/assets/8e5daf46-8dd0-4221-984b-5a32b79866b3

**Anything else**
Anything else you can add to supplement the report

**Comment by Hoto-Mocha** [comment]
fixed in v3.18.0. thanks.
